//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRobotConfiguration
    {
        public System.Guid TestRobotConfigurationID { get; set; }
        public System.Guid TestRobotID { get; set; }
        public System.Guid TestMicroControllerID { get; set; }
        public System.Guid TestRobotActionAsscociatedID { get; set; }
        public string RobotConfigurationDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
