//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestClass
    {
        public System.Guid TestClassID { get; set; }
        public string TestClassName { get; set; }
        public System.Guid TestAssemblyID { get; set; }
        public string TestClassDescription { get; set; }
        public System.DateTime ClassCreationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
