//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTargetFrameworkVersion
    {
        public System.Guid VersionID { get; set; }
        public string FrameWorkVersionName { get; set; }
        public System.Guid TargetFrameworkID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
