//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCycle
    {
        public System.Guid TestCycleID { get; set; }
        public System.Guid TestCaseID { get; set; }
        public System.Guid NextTestCaseID { get; set; }
        public Nullable<System.DateTime> CycleStoppedDateTime { get; set; }
        public Nullable<bool> IsRunning { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
