//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAssembly
    {
        public System.Guid TestAssemblyID { get; set; }
        public string TestAssemblyName { get; set; }
        public string TestAssemblyExtJarFileOrDll { get; set; }
        public string TestAssemblyFullName { get; set; }
        public System.DateTime AssemblyCreationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
